[general]
import = ["~/.config/alacritty/themes/themes/nord.toml"]
live_config_reload = true
[window]
dimensions = { lines = 80, columns = 240 }
opacity = 0.7
blur = true
resize_increments = true
[scrolling]
history = 50000
[font]
size = 10
